-- PV_Dictionary v0.0.1 — Supabase schema
--
-- 執行方式：貼進 Supabase SQL Editor 執行（整份 idempotent，可以重複跑）。
-- 使用時機：v0.1.0 實作 DATA_BACKEND=supabase 時。
--
-- 設計原則：
--   * 前端永不直連資料庫；伺服器用 service_role key，所以這裡對所有表開啟 RLS 且「不加 policy」，
--     並撤銷 anon / authenticated 的權限（service_role 會繞過 RLS）。
--   * 表名一律加 dict_ 前綴，避免與同一個 Supabase 專案的其他應用衝突。

-- ---------- 書本 ----------
create table if not exists public.dict_books (
    id            bigint generated by default as identity primary key,
    code          text not null unique,
    name          text not null,
    grade         text,
    publisher     text,
    sort_order    int not null default 0,
    is_published  boolean not null default true,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

-- ---------- 單元 ----------
create table if not exists public.dict_units (
    id           bigint generated by default as identity primary key,
    book_id      bigint not null references public.dict_books(id) on delete cascade,
    unit_no      int not null,
    title        text,
    sort_order   int not null default 0,
    is_published boolean not null default true,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz,
    unique (book_id, unit_no)
);

-- ---------- 生字 ----------
create table if not exists public.dict_entries (
    id             bigint generated by default as identity primary key,
    unit_id        bigint not null references public.dict_units(id) on delete cascade,
    headword       text not null,
    headword_norm  text not null,
    ipa_us         text,
    ipa_uk         text,
    part_of_speech text,
    zh_meaning     text,
    en_definition  text,
    example_en     text,
    example_zh     text,
    status         text not null default 'published',   -- published | pending | draft | rejected
    review_note    text,
    reviewed_by    text,
    reviewed_at    timestamptz,
    sort_order     int not null default 0,
    created_by     text,
    updated_by     text,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz,
    unique (unit_id, headword_norm)
);

-- ---------- 老師錄音 ----------
create table if not exists public.dict_audio (
    id          bigint generated by default as identity primary key,
    entry_id    bigint not null references public.dict_entries(id) on delete cascade,
    source      text not null default 'teacher',        -- teacher | tts
    accent      text,
    mime        text not null,
    bytes       int not null,
    duration_ms int,
    data        text not null,                          -- base64，單筆上限 1MB
    uploaded_by text,
    created_at  timestamptz not null default now()
);

-- ---------- 使用者 ----------
create table if not exists public.dict_users (
    id            bigint generated by default as identity primary key,
    username      text not null unique,
    display_name  text,
    password_hash text not null,                        -- scrypt$salt$hash（CSPRNG salt）
    role          text not null default 'student',
    is_active     boolean not null default true,
    last_login_at timestamptz,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

-- ---------- 單元級授權（「授權的人」） ----------
create table if not exists public.dict_grants (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    book_id     bigint,
    unit_id     bigint,
    can_edit    boolean not null default true,
    can_publish boolean not null default false,
    granted_by  text,
    created_at  timestamptz not null default now()
);

-- ---------- 稽核 ----------
create table if not exists public.dict_audit_logs (
    id           bigint generated by default as identity primary key,
    user_id      text,
    display_name text,
    role         text,
    action       text not null,
    target_id    text,
    details      text,
    ip           text,
    created_at   timestamptz not null default now()
);

-- ---------- 索引 ----------
create index if not exists dict_units_book_idx on public.dict_units (book_id);
create index if not exists dict_entries_unit_idx on public.dict_entries (unit_id, sort_order);
create index if not exists dict_entries_status_idx on public.dict_entries (status);
create index if not exists dict_audio_entry_idx on public.dict_audio (entry_id);
create index if not exists dict_audit_created_idx on public.dict_audit_logs (created_at desc);
create index if not exists dict_grants_user_idx on public.dict_grants (user_id);

-- ---------- 鎖住 anon / authenticated（伺服器用 service_role，會繞過 RLS） ----------
alter table public.dict_books      enable row level security;
alter table public.dict_units      enable row level security;
alter table public.dict_entries    enable row level security;
alter table public.dict_audio      enable row level security;
alter table public.dict_users      enable row level security;
alter table public.dict_grants     enable row level security;
alter table public.dict_audit_logs enable row level security;

revoke all on public.dict_books, public.dict_units, public.dict_entries, public.dict_audio,
    public.dict_users, public.dict_grants, public.dict_audit_logs
    from anon, authenticated;

-- ---------- 回滾（出事時貼上執行） ----------
-- drop table if exists public.dict_grants;
-- drop table if exists public.dict_audit_logs;
-- drop table if exists public.dict_audio;
-- drop table if exists public.dict_entries;
-- drop table if exists public.dict_units;
-- drop table if exists public.dict_users;
-- drop table if exists public.dict_books;
