-- PV_Dictionary v0.3.2 — 把 id 的 identity sequence 校正到 max(id)
--
-- 為什麼需要：本專案的資料一律「自己配 id」寫入（`generated by default as identity`
-- 只有在 INSERT 不給 id 時才會動到 sequence）。所以只要曾經帶 id 寫過，
-- sequence 就會停在 1，之後任何「不給 id 的 INSERT」都會撞到既有的 id：
--   duplicate key value violates unique constraint "dict_books_pkey"  Key (id)=(1) already exists
-- App 本身沒問題（它每次都用 max(id)+1），但用 Supabase 介面或腳本補資料時就會踩到。
--
-- 執行方式：Supabase → SQL Editor 貼上執行（idempotent，可重複跑）。

select setval(pg_get_serial_sequence('public.dict_books', 'id'),
              greatest(coalesce((select max(id) from public.dict_books), 1), 1));
select setval(pg_get_serial_sequence('public.dict_units', 'id'),
              greatest(coalesce((select max(id) from public.dict_units), 1), 1));
select setval(pg_get_serial_sequence('public.dict_entries', 'id'),
              greatest(coalesce((select max(id) from public.dict_entries), 1), 1));
select setval(pg_get_serial_sequence('public.dict_audio', 'id'),
              greatest(coalesce((select max(id) from public.dict_audio), 1), 1));
select setval(pg_get_serial_sequence('public.dict_users', 'id'),
              greatest(coalesce((select max(id) from public.dict_users), 1), 1));
select setval(pg_get_serial_sequence('public.dict_grants', 'id'),
              greatest(coalesce((select max(id) from public.dict_grants), 1), 1));
select setval(pg_get_serial_sequence('public.dict_audit_logs', 'id'),
              greatest(coalesce((select max(id) from public.dict_audit_logs), 1), 1));
