-- v0.4.2：錯誤日誌（A-5）＋ 稽核紀錄的自動化檢查標記（E-4）
--
-- 錯誤日誌為什麼要獨立一張表、而不是塞進 dict_audit_logs：
--   1. 稽核是「誰做了什麼」（有法律／責任意義，要保留）；錯誤日誌是「系統哪裡壞了」（可清理、可標記已處理）。
--   2. 這張表不進 hydrate 快取（見 lib/store/index.js 的 TABLE_NAMES），
--      因為它會一直長大，而且只在後台檢視時才需要讀。
--
-- 不含任何截圖欄位（使用者指定：不用保存截圖）；context 只放白名單欄位（行號、錯誤類型…）。

create table if not exists public.dict_error_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source text not null default 'client',
    level text not null default 'error',
    code text not null default '',
    message text not null default '',
    path text not null default '',
    version text not null default '',
    user_id bigint,
    display_name text not null default '',
    user_agent text not null default '',
    is_self_test boolean not null default false,
    context jsonb,
    resolved boolean not null default false,
    resolved_by bigint,
    resolved_at timestamptz,
    resolved_note text not null default ''
);

create index if not exists dict_error_logs_created_at_idx on public.dict_error_logs (created_at desc);
create index if not exists dict_error_logs_resolved_idx on public.dict_error_logs (resolved);

-- 自動化檢查（scripts/live-verify.js 等）帶簽章標頭時，稽核紀錄會標成 is_self_test=true，
-- 預設檢視可以把它藏起來 —— 否則每次驗收都在你的稽核紀錄裡留下十幾筆假動作。
alter table public.dict_audit_logs add column if not exists is_self_test boolean not null default false;

-- ★ 與其他表同一套保護：新表一定要自己鎖（Supabase 對 public schema 的新表預設會給
--   anon／authenticated 權限，不鎖就等於把錯誤日誌公開給任何拿到 anon key 的人）。
alter table public.dict_error_logs enable row level security;
revoke all on public.dict_error_logs from anon, authenticated;

-- ---------- 回滾（出事時貼上執行） ----------
-- drop table if exists public.dict_error_logs;
-- alter table public.dict_audit_logs drop column if exists is_self_test;
