-- v0.8.0（Neon 影子驗證）：Neon 版的 schema
--
-- 為什麼要另寫一份、而不是直接貼 migrations/*.sql：
--   1. Supabase 的遷移檔裡有 `revoke all on ... from anon, authenticated` —— 這兩個角色是 Supabase
--      才有的，**Neon 沒有這兩個角色**，直接貼會 `role "anon" does not exist` 而中斷。
--   2. 這裡改成對 `public` 撤銷權限（每個 Postgres 都有），效果相同：只有專案擁有者／
--      我們自己發的 JWT 角色能碰這些表。
--   3. 其餘（表、欄位、索引、函式）刻意與 Supabase 版**完全一致**，影子驗證才有意義。
--
-- 執行方式：`connectors__neon_mcp__RUN_SQL_TRANSACTION`（或貼進 Neon SQL Editor），整份 idempotent。
-- 目標專案：Gary-dictionary（`still-dawn-90059323`，region `aws-ap-southeast-1`）。

-- ---------- 書本 ----------
create table if not exists public.dict_books (
    id            bigint generated by default as identity primary key,
    code          text not null unique,
    name          text not null,
    grade         text,
    publisher     text,
    sort_order    int not null default 0,
    is_published  boolean not null default true,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

-- ---------- 單元 ----------
create table if not exists public.dict_units (
    id           bigint generated by default as identity primary key,
    book_id      bigint not null references public.dict_books(id) on delete cascade,
    unit_no      int not null,
    title        text,
    sort_order   int not null default 0,
    is_published boolean not null default true,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz,
    unique (book_id, unit_no)
);

-- ---------- 生字 ----------
create table if not exists public.dict_entries (
    id             bigint generated by default as identity primary key,
    unit_id        bigint not null references public.dict_units(id) on delete cascade,
    headword       text not null,
    headword_norm  text not null,
    ipa_us         text,
    ipa_uk         text,
    part_of_speech text,
    zh_meaning     text,
    en_definition  text,
    example_en     text,
    example_zh     text,
    status         text not null default 'published',
    review_note    text,
    reviewed_by    text,
    reviewed_at    timestamptz,
    sort_order     int not null default 0,
    created_by     text,
    updated_by     text,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz,
    unique (unit_id, headword_norm)
);

-- ---------- 老師錄音 ----------
create table if not exists public.dict_audio (
    id          bigint generated by default as identity primary key,
    entry_id    bigint not null references public.dict_entries(id) on delete cascade,
    source      text not null default 'teacher',
    accent      text,
    mime        text not null,
    bytes       int not null,
    duration_ms int,
    data        text not null,
    uploaded_by text,
    created_at  timestamptz not null default now()
);

-- ---------- 使用者 ----------
create table if not exists public.dict_users (
    id            bigint generated by default as identity primary key,
    username      text not null unique,
    display_name  text,
    password_hash text not null,
    role          text not null default 'student',
    is_active     boolean not null default true,
    last_login_at timestamptz,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

-- ---------- 單元級授權 ----------
create table if not exists public.dict_grants (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    book_id     bigint,
    unit_id     bigint,
    can_edit    boolean not null default true,
    can_publish boolean not null default false,
    granted_by  text,
    created_at  timestamptz not null default now()
);

-- ---------- 稽核 ----------
create table if not exists public.dict_audit_logs (
    id           bigint generated by default as identity primary key,
    user_id      text,
    display_name text,
    role         text,
    action       text not null,
    target_id    text,
    details      text,
    ip           text,
    created_at   timestamptz not null default now()
);

-- ---------- 錯誤日誌（不進 hydrate 快取） ----------
create table if not exists public.dict_error_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source text not null default 'client',
    level text not null default 'error',
    code text not null default '',
    message text not null default '',
    path text not null default '',
    version text not null default '',
    user_id bigint,
    display_name text not null default '',
    user_agent text not null default '',
    is_self_test boolean not null default false,
    context jsonb,
    resolved boolean not null default false,
    resolved_by bigint,
    resolved_at timestamptz,
    resolved_note text not null default ''
);

-- ---------- 舊欄位與後續版本補上的欄位（與 Supabase 版一致） ----------
alter table public.dict_books add column if not exists cover_mime       text;
alter table public.dict_books add column if not exists cover_data       text;
alter table public.dict_books add column if not exists cover_bytes      int not null default 0;
alter table public.dict_books add column if not exists cover_updated_at timestamptz;
alter table public.dict_books add column if not exists cover_by         text;

alter table public.dict_audit_logs add column if not exists is_self_test boolean not null default false;

alter table public.dict_users add column if not exists token_version integer not null default 1;
alter table public.dict_users add column if not exists totp_secret text not null default '';
alter table public.dict_users add column if not exists totp_enabled_at timestamptz;
alter table public.dict_users add column if not exists backup_codes jsonb;
alter table public.dict_users add column if not exists last_login_ip text not null default '';
alter table public.dict_users add column if not exists last_login_agent text not null default '';

-- ---------- 索引 ----------
create index if not exists dict_units_book_idx on public.dict_units (book_id);
create index if not exists dict_entries_unit_idx on public.dict_entries (unit_id, sort_order);
create index if not exists dict_entries_status_idx on public.dict_entries (status);
create index if not exists dict_audio_entry_idx on public.dict_audio (entry_id);
create index if not exists dict_audit_created_idx on public.dict_audit_logs (created_at desc);
create index if not exists dict_grants_user_idx on public.dict_grants (user_id);
create index if not exists dict_error_logs_created_at_idx on public.dict_error_logs (created_at desc);
create index if not exists dict_error_logs_resolved_idx on public.dict_error_logs (resolved);

-- ---------- v0.7.0 的兩個函式（與 Supabase 線上一致） ----------
create or replace function public.dict_entry_counts(unit_ids bigint[])
returns table (unit_id bigint, status text, n integer)
language sql
stable
as $$
    select e.unit_id, e.status, count(*)::int as n
    from public.dict_entries e
    where unit_ids is null or e.unit_id = any(unit_ids)
    group by e.unit_id, e.status;
$$;

create or replace function public.dict_db_size()
returns bigint
language sql
stable
as $$
    select pg_database_size(current_database())::bigint;
$$;

-- ---------- 鎖住：Neon 沒有 anon／authenticated 角色，改成對 PUBLIC 撤銷 ----------
alter table public.dict_books       enable row level security;
alter table public.dict_units       enable row level security;
alter table public.dict_entries     enable row level security;
alter table public.dict_audio       enable row level security;
alter table public.dict_users       enable row level security;
alter table public.dict_grants      enable row level security;
alter table public.dict_audit_logs  enable row level security;
alter table public.dict_error_logs  enable row level security;

revoke all on public.dict_books, public.dict_units, public.dict_entries, public.dict_audio,
    public.dict_users, public.dict_grants, public.dict_audit_logs, public.dict_error_logs
    from public;

revoke all on function public.dict_entry_counts(bigint[]) from public;
revoke all on function public.dict_db_size() from public;

-- ---------- 回滾（出事時貼上執行） ----------
-- drop table if exists public.dict_error_logs;
-- drop table if exists public.dict_grants;
-- drop table if exists public.dict_audit_logs;
-- drop table if exists public.dict_audio;
-- drop table if exists public.dict_entries;
-- drop table if exists public.dict_units;
-- drop table if exists public.dict_users;
-- drop table if exists public.dict_books;
