/* Supabase（PostgreSQL）資料層
 *
 * ★ 為什麼寫成「每次請求先抓下來 → 同步給程式用 → 回應前寫回去」：
 *   這個專案的路由是同步風格（上百處 `store.xxx()` 直接取值），改成非同步會動到所有路由；
 *   而且 serverless（Vercel）在回應送出後會凍結實例，**不能在回應之後才寫資料庫**。
 *   所以：
 *     1. `/api/*` 進來時先 hydrate()：把 7 張表抓進記憶體（連 id 最大值，用來本地配 id）。
 *     2. 路由照舊同步讀寫記憶體；新增的列由本地配 id（schema 用的是 `generated by default as identity`，
 *        所以可以把 id 一起 INSERT 進去，這樣 Postgres 配的 id 與我們回給前端的 id 一致）。
 *     3. 回應「送出之前」flush()：把異動按外鍵順序寫回 Supabase。
 *        寫回失敗就回 500（不假裝成功）。
 *
 * ★ 已知代價（與本機 JSON 版相同）：同一瞬間的兩個請求會互相覆蓋（後寫的贏）。
 *   學校規模的編輯情境（幾位老師同時加生字）可以接受；要真正解決需要改成資料庫層的交易與版本欄位。
 */
const TABLES = ['books', 'units', 'entries', 'audio', 'users', 'grants', 'audit_logs'];
const TABLE_PREFIX = 'dict_';

/* 寫入順序（外鍵：books → units → entries → audio；users → grants；audit 最後） */
const INSERT_ORDER = ['books', 'units', 'entries', 'audio', 'users', 'grants', 'audit_logs'];
/* 刪除順序剛好相反（先刪子表） */
const DELETE_ORDER = INSERT_ORDER.slice().reverse();

function createSupabaseStore(options = {}) {
    const url = String(options.url || process.env.SUPABASE_URL || '').replace(/\/+$/, '');
    const key = String(options.key || process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY || '');
    if (!url || !key) {
        const err = new Error('DATA_BACKEND=supabase 需要 SUPABASE_URL 與 SUPABASE_SERVICE_ROLE_KEY');
        err.code = 'SUPABASE_CONFIG_MISSING';
        throw err;
    }
    /* 佔位值等於沒有金鑰：寧可當場炸掉，也不要讓它跑起來之後每個請求都 401 */
    if (/^REPLACE_ME/.test(url) || /^REPLACE_ME/.test(key)) {
        const err = new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY 還是 REPLACE_ME 佔位值，請填入真正的值');
        err.code = 'SUPABASE_CONFIG_PLACEHOLDER';
        throw err;
    }

    let state = {};
    let nextId = {};
    let ops = [];
    let hydrated = false;
    let hydratedAt = 0;
    let hydrating = null;
    let lastError = null;

    function emptyState() {
        const out = {};
        for (const name of TABLES) out[name] = [];
        return out;
    }

    function reset() {
        state = emptyState();
        nextId = {};
        ops = [];
        for (const name of TABLES) nextId[name] = 1;
        hydrated = false;
        hydratedAt = 0;
        hydrating = null;
    }
    reset();

    async function request(path, { method = 'GET', body, prefer } = {}) {
        const headers = {
            apikey: key,
            Authorization: `Bearer ${key}`,
            Accept: 'application/json'
        };
        if (body !== undefined) headers['Content-Type'] = 'application/json';
        if (prefer) headers.Prefer = prefer;
        const res = await fetch(`${url}/rest/v1/${path}`, {
            method,
            headers,
            body: body === undefined ? undefined : JSON.stringify(body)
        });
        const text = await res.text();
        let data = null;
        if (text) {
            try { data = JSON.parse(text); } catch (err) { data = text; }
        }
        if (!res.ok) {
            const message = (data && (data.message || data.hint || data.error)) || `HTTP ${res.status}`;
            const err = new Error(`Supabase ${method} ${path} → ${message}`);
            err.code = 'SUPABASE_REQUEST_FAILED';
            err.status = res.status;
            throw err;
        }
        return data;
    }

    /* 每次請求都重新抓一次（ttl 預設 0）：7 個並行查詢在學校規模下很便宜，
     * 但「別的實例／別的瀏覽器剛寫進去的東西看不到」對教學用途是災難（老師加了生字、學生看不到）。
     * 想省查詢量可以用 SUPABASE_HYDRATE_TTL_MS 設一個毫秒數（例如 2000）。 */
    const hydrateTtlMs = (() => {
        const fromOptions = Number(options.hydrateTtlMs);
        if (Number.isFinite(fromOptions) && options.hydrateTtlMs !== undefined) return fromOptions;
        const fromEnv = Number(process.env.SUPABASE_HYDRATE_TTL_MS);
        return Number.isFinite(fromEnv) ? fromEnv : 0;
    })();

    async function hydrate() {
        /* 還有沒寫回的異動時不要重抓：重抓會把 state 換掉，那些寫入就憑空消失了 */
        if (ops.length) return state;
        if (hydrated && Date.now() - hydratedAt < hydrateTtlMs) return state;
        if (hydrating) return hydrating;
        hydrating = (async () => {
            const fresh = emptyState();
            try {
                const results = await Promise.all(TABLES.map((name) => request(
                    `${TABLE_PREFIX}${name}?select=*&order=id.asc`,
                    { prefer: 'count=exact' }
                )));
                TABLES.forEach((name, index) => {
                    const rows = Array.isArray(results[index]) ? results[index] : [];
                    fresh[name] = rows;
                    const maxId = rows.reduce((max, row) => Math.max(max, Number(row.id) || 0), 0);
                    nextId[name] = maxId + 1;
                });
                lastError = null;
            } catch (err) {
                lastError = { message: err.message, code: err.code || null, status: err.status || null, at: new Date().toISOString() };
                hydrating = null;
                throw err;
            }
            state = fresh;
            ops = [];
            hydrated = true;
            hydratedAt = Date.now();
            hydrating = null;
            return state;
        })();
        return hydrating;
    }

    /* 診斷用：只吐「不含機密」的資訊（主機代號、金鑰的角色與所屬專案 ref、最後一次錯誤）。
     * ★ 不要把金鑰本身或它的雜湊放進來 —— /api/health 是公開端點。 */
    function diagnostics() {
        let role = null;
        let ref = null;
        let format = 'jwt';
        try {
            const payload = JSON.parse(Buffer.from(String(key).split('.')[1] || '', 'base64url').toString('utf8'));
            role = payload.role || null;
            ref = payload.ref || null;
        } catch (err) {
            format = 'not-a-jwt';
        }
        return {
            host: String(url).replace(/^https?:\/\//, '').split('.')[0] || null,
            key_role: role,
            key_ref: ref,
            key_format: format,
            hydrate_ok: !lastError,
            last_error: lastError
        };
    }

    /* 把某張表的異動寫回；一次一筆，順序固定（外鍵不會踩到） */
    async function applyOps(list) {
        for (const op of list) {
            const table = `${TABLE_PREFIX}${op.table}`;
            if (op.kind === 'insert') {
                await request(table, { method: 'POST', body: op.row, prefer: 'return=minimal' });
            } else if (op.kind === 'update') {
                await request(`${table}?id=eq.${encodeURIComponent(op.id)}`, { method: 'PATCH', body: op.patch, prefer: 'return=minimal' });
            } else if (op.kind === 'delete') {
                await request(`${table}?id=eq.${encodeURIComponent(op.id)}`, { method: 'DELETE', prefer: 'return=minimal' });
            }
        }
    }

    async function flush() {
        if (!ops.length) return { written: 0 };
        const pending = ops;
        ops = [];
        const ordered = [
            ...pending.filter((op) => op.kind === 'delete').sort((a, b) => DELETE_ORDER.indexOf(a.table) - DELETE_ORDER.indexOf(b.table)),
            ...pending.filter((op) => op.kind === 'insert').sort((a, b) => INSERT_ORDER.indexOf(a.table) - INSERT_ORDER.indexOf(b.table)),
            ...pending.filter((op) => op.kind === 'update')
        ];
        try {
            await applyOps(ordered);
        } catch (err) {
            /* 失敗就把異動丟掉、並讓下一次請求重新 hydrate：
             * 記憶體不可以留著「其實沒寫進資料庫」的假資料（會讓使用者以為存好了）。 */
            ops = [];
            hydrated = false;
            throw err;
        }
        return { written: ordered.length };
    }

    /* ---------- 內部：讀寫記憶體 ---------- */
    const clone = (value) => (value === undefined || value === null ? value : JSON.parse(JSON.stringify(value)));

    function rows(table) { return state[table] || (state[table] = []); }

    function insert(table, data) {
        const row = Object.assign({}, data);
        if (row.id === undefined || row.id === null) {
            row.id = nextId[table] || 1;
            nextId[table] = row.id + 1;
        }
        if (row.created_at === undefined) row.created_at = new Date().toISOString();
        rows(table).push(row);
        ops.push({ kind: 'insert', table, row: clone(row) });
        return clone(row);
    }

    function update(table, id, patch) {
        const list = rows(table);
        const row = list.find((r) => String(r.id) === String(id));
        if (!row) return null;
        Object.assign(row, patch, { updated_at: new Date().toISOString() });
        ops.push({ kind: 'update', table, id: row.id, patch: Object.assign({}, patch, { updated_at: row.updated_at }) });
        return clone(row);
    }

    function remove(table, id) {
        const list = rows(table);
        const index = list.findIndex((r) => String(r.id) === String(id));
        if (index === -1) return false;
        list.splice(index, 1);
        ops.push({ kind: 'delete', table, id });
        return true;
    }

    function sorted(table, compare) {
        return rows(table).slice().sort(compare).map(clone);
    }

    /* ---------- 書本 ---------- */
    function listBooks({ includeUnpublished = false } = {}) {
        return sorted('books', (a, b) => (a.sort_order - b.sort_order) || (a.id - b.id))
            .filter((b) => includeUnpublished || b.is_published !== false);
    }
    function getBook(id) { return clone(rows('books').find((b) => String(b.id) === String(id))) || null; }
    function createBook(data) { return insert('books', data); }
    function updateBook(id, patch) { return update('books', id, patch); }

    /* ---------- 單元 ---------- */
    function listUnits({ bookId = null, includeUnpublished = false } = {}) {
        return sorted('units', (a, b) => (a.unit_no - b.unit_no) || (a.id - b.id))
            .filter((u) => (bookId === null || String(u.book_id) === String(bookId)))
            .filter((u) => includeUnpublished || u.is_published !== false);
    }
    function getUnit(id) { return clone(rows('units').find((u) => String(u.id) === String(id))) || null; }
    function findUnitByNo(bookId, unitNo) {
        return clone(rows('units').find((u) => String(u.book_id) === String(bookId) && Number(u.unit_no) === Number(unitNo))) || null;
    }
    function createUnit(data) { return insert('units', data); }
    function updateUnit(id, patch) { return update('units', id, patch); }

    /* ---------- 生字 ---------- */
    function listEntries({ unitId = null, statuses = null } = {}) {
        return sorted('entries', (a, b) => (a.sort_order - b.sort_order) || (a.id - b.id))
            .filter((e) => (unitId === null || String(e.unit_id) === String(unitId)))
            .filter((e) => !statuses || statuses.includes(e.status));
    }
    function getEntry(id) { return clone(rows('entries').find((e) => String(e.id) === String(id))) || null; }
    function findEntryByHeadword(unitId, headwordNorm) {
        return clone(rows('entries').find((e) => String(e.unit_id) === String(unitId) && e.headword_norm === headwordNorm)) || null;
    }
    function createEntry(data) { return insert('entries', data); }
    function updateEntry(id, patch) { return update('entries', id, patch); }
    function deleteEntry(id) {
        const ok = remove('entries', id);
        if (ok) {
            for (const audio of rows('audio').filter((a) => String(a.entry_id) === String(id))) remove('audio', audio.id);
        }
        return ok;
    }
    function countEntries(unitId, statuses) {
        return rows('entries')
            .filter((e) => String(e.unit_id) === String(unitId))
            .filter((e) => !statuses || statuses.includes(e.status)).length;
    }

    /* ---------- 音檔 ---------- */
    function listAudio({ entryId = null } = {}) {
        return rows('audio')
            .filter((a) => (entryId === null || String(a.entry_id) === String(entryId)))
            .map(clone);
    }
    function getAudio(id) { return clone(rows('audio').find((a) => String(a.id) === String(id))) || null; }
    function createAudio(data) { return insert('audio', data); }
    function deleteAudio(id) { return remove('audio', id); }
    function findTeacherAudio(entryId) {
        return clone(rows('audio').find((a) => String(a.entry_id) === String(entryId) && a.source === 'teacher')) || null;
    }

    /* ---------- 使用者 ---------- */
    function findUserByUsername(username) {
        const key2 = String(username || '').trim().toLowerCase();
        return clone(rows('users').find((u) => String(u.username || '').toLowerCase() === key2)) || null;
    }
    function getUser(id) { return clone(rows('users').find((u) => String(u.id) === String(id))) || null; }
    function listUsers() { return sorted('users', (a, b) => a.id - b.id); }
    function createUser(data) { return insert('users', data); }
    function updateUser(id, patch) { return update('users', id, patch); }
    function deleteUser(id) { return remove('users', id); }
    function countUsersByRole(role) {
        return rows('users').filter((u) => u.role === role && u.is_active !== false).length;
    }

    /* ---------- 授權 ---------- */
    function listGrants({ userId = null } = {}) {
        return rows('grants')
            .filter((g) => (userId === null || String(g.user_id) === String(userId)))
            .map(clone);
    }
    function createGrant(data) { return insert('grants', data); }
    function deleteGrant(id) { return remove('grants', id); }

    /* ---------- 稽核 ---------- */
    function insertAuditLog(row) { return insert('audit_logs', row); }
    function listAuditLogs({ limit = 50, offset = 0, q = '' } = {}) {
        const needle = String(q || '').trim().toLowerCase();
        const matched = rows('audit_logs')
            .filter((r) => {
                if (!needle) return true;
                return [r.action, r.user_id, r.display_name, r.details, r.target_id]
                    .some((value) => String(value || '').toLowerCase().includes(needle));
            })
            .sort((a, b) => (a.created_at < b.created_at ? 1 : a.created_at > b.created_at ? -1 : b.id - a.id));
        const page = matched.slice(offset, offset + limit).map(clone);
        return { items: page, total: matched.length, limit, offset, has_more: matched.length > offset + limit };
    }

    function tableCounts() {
        const counts = {};
        for (const name of TABLES) counts[name] = rows(name).length;
        return counts;
    }

    return {
        backend: 'supabase',
        dataFile: null,
        normalizeHeadword: require('./index').normalizeHeadword,
        hydrate,
        flush,
        diagnostics,
        listBooks, getBook, createBook, updateBook,
        listUnits, getUnit, findUnitByNo, createUnit, updateUnit,
        listEntries, getEntry, findEntryByHeadword, createEntry, updateEntry, deleteEntry, countEntries,
        listAudio, getAudio, createAudio, deleteAudio, findTeacherAudio,
        findUserByUsername, getUser, listUsers, createUser, updateUser, deleteUser, countUsersByRole,
        listGrants, createGrant, deleteGrant,
        insertAuditLog, listAuditLogs,
        tableCounts,
        reload: reset,
        pendingOps: () => ops.length,
        _raw: () => clone(state)
    };
}

module.exports = { createSupabaseStore, TABLES, INSERT_ORDER, DELETE_ORDER };
