/* Supabase（PostgreSQL）資料層
 *
 * ★ 為什麼寫成「先抓下來 → 同步給程式用 → 回應前寫回去」：
 *   這個專案的路由是同步風格（上百處 `store.xxx()` 直接取值），改成非同步會動到所有路由；
 *   而且 serverless（Vercel）在回應送出後會凍結實例，**不能在回應之後才寫資料庫**。
 *   所以：
 *     1. `/api/*` 進來時先 hydrate()：抓**小表**（books／units／users／grants）進記憶體，並配好 id。
 *     2. 再 `prefetch(spec)`：只抓這條路由真正會用到的**生字／音檔／稽核切片**（視窗）。
 *     3. 路由照舊同步讀寫；新增的列由本地配 id（schema 是 `generated by default as identity`，
 *        可以把 id 一起 INSERT，Postgres 配的 id 與回給前端的 id 一致）。
 *     4. 回應「送出之前」flush()：把異動按外鍵順序寫回 Supabase；寫回失敗回 500（不假裝成功）。
 *
 * ★ 已知代價（與本機 JSON 版相同）：同一瞬間的兩個請求會互相覆蓋（後寫的贏）。
 *   學校規模的編輯情境（幾位老師同時加生字）可以接受；要真正解決需要改成資料庫層的交易與版本欄位。
 */
/* 小表：每次請求都抓（幾十到幾百列，變動慢）
 * ★ v0.6.1：生字（entries）／音檔（audio）／稽核（audit_logs）**不再整表抓**，
 *   改成「這次請求需要哪一塊才抓哪一塊」——見 prefetch() 與視窗存取器。 */
const HYDRATE_TABLES = ['books', 'units', 'users', 'grants'];
const WINDOW_TABLES = ['entries', 'audio', 'audit_logs'];
const TABLES = [...HYDRATE_TABLES, ...WINDOW_TABLES];
const TABLE_PREFIX = 'dict_';

const { normalizeAuditFilters, matchesAuditFilters } = require('../audit');
const { HAS_UPDATED_AT } = require('../schema');

/* ★ 不要把 base64 大欄位抓進記憶體：一本書的封面可能 2MB、一段錄音 1MB，
 *   每次請求都把它們全部抓下來，等於每個 /api 請求都要傳幾 MB ——
 *   老師錄 10 段音之後，整站會慢到不能用。改成：清單／一般讀取只拿中繼資料，
 *   真的要檔案時（GET /api/covers/:id、GET /api/audio/:id）才單筆抓。
 *   `audio.data` / `books.cover_data` 在記憶體裡一律是 null。 */
const SELECT_COLUMNS = {
    books: 'id,code,name,grade,publisher,sort_order,is_published,created_at,updated_at,cover_mime,cover_bytes,cover_updated_at,cover_by',
    audio: 'id,entry_id,source,accent,mime,bytes,duration_ms,uploaded_by,created_at'
};
const HEAVY_FIELDS = { books: 'cover_data', audio: 'data' };

/* 寫入順序（外鍵：books → units → entries → audio；users → grants；audit 最後） */
const INSERT_ORDER = ['books', 'units', 'entries', 'audio', 'users', 'grants', 'audit_logs'];
/* 刪除順序剛好相反（先刪子表） */
const DELETE_ORDER = INSERT_ORDER.slice().reverse();

function createSupabaseStore(options = {}) {
    const url = String(options.url || process.env.SUPABASE_URL || '').replace(/\/+$/, '');
    const key = String(options.key || process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY || '');
    if (!url || !key) {
        const err = new Error('DATA_BACKEND=supabase 需要 SUPABASE_URL 與 SUPABASE_SERVICE_ROLE_KEY');
        err.code = 'SUPABASE_CONFIG_MISSING';
        throw err;
    }
    /* 佔位值等於沒有金鑰：寧可當場炸掉，也不要讓它跑起來之後每個請求都 401 */
    if (/^REPLACE_ME/.test(url) || /^REPLACE_ME/.test(key)) {
        const err = new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY 還是 REPLACE_ME 佔位值，請填入真正的值');
        err.code = 'SUPABASE_CONFIG_PLACEHOLDER';
        throw err;
    }

    /* 請求上下文：AsyncLocalStorage（不能用模組變數 —— 兩個請求會在 await 交錯） */
    const { AsyncLocalStorage } = require('node:async_hooks');
    const als = new AsyncLocalStorage();

    let state = {};
    let nextId = {};
    let ops = [];
    let hydrated = false;
    let hydratedAt = 0;
    let hydrating = null;
    let lastError = null;

    /* 目前這個請求抓了哪些範圍（沒有請求上下文時＝null，代表 full 模式：整表都算已載入） */
    function newWindow() {
        return {
            /* ★ 這幾張表的「工作集」：prefetch 抓進來的 + 這個請求自己新增／改／刪的都放這裡。
             *   不放在 state 的原因：state 是實例共用的，兩個請求交錯時會互相污染。 */
            entries: [],
            audio: [],
            audit: [],
            entryCounts: [],              /* {unit_id, status, n}（只為了算數字，不搬整列） */
            entriesAll: false,            /* 已載入「全部生字」（只有 full 模式或明示） */
            entryUnits: new Set(),        /* 已載入整批生字的單元 id */
            entryIds: new Set(),          /* 已載入的單筆生字 id */
            createdEntryIds: new Set(),   /* 這個請求新建的生字（音檔視窗當然是空的） */
            audioEntries: new Set(),      /* 已載入音檔的生字 id */
            audioAll: false,
            countsLoaded: false,          /* 生字數（單位 × 狀態）是否已載入 */
            auditLoaded: false,
            auditTotal: 0,
            auditFingerprint: null,       /* 稽核視窗是照哪一組篩選抓的 */
            totals: null                  /* 各表筆數（/api/health 用） */
        };
    }
    /* 重型表的工作集：有請求上下文用視窗，沒有（腳本／測試）用 state */
    function heavyRows(table) {
        const w = win();
        if (!w) return rows(table);
        if (table === 'entries') return w.entries;
        if (table === 'audio') return w.audio;
        if (table === 'audit_logs') return w.audit;
        return rows(table);
    }
    function win() { return als.getStore() || null; }
    function needsWindow(what) {
        /* full 模式（腳本／測試）沒有視窗，照舊全部可用 */
        const w = win();
        if (!w) return null;
        return w;
    }
    function windowMissing(what) {
        const err = new Error(
            `Supabase 資料層：這次請求沒有載入「${what}」的資料（視窗化資料層的安全機制）。` +
            '請在 /api middleware 的 prefetch() 加上這條路由需要抓什麼 —— 寧可大聲失敗，也不要靜默回空資料。'
        );
        err.code = 'STORE_WINDOW_MISSING';
        err.status = 500;
        return err;
    }
    function requireEntriesOfUnit(unitId) {
        const w = needsWindow('entries');
        if (!w) return;
        if (w.entriesAll || w.entryUnits.has(String(unitId))) return;
        throw windowMissing(`單元 ${unitId} 的生字`);
    }
    function requireEntry(id) {
        const w = needsWindow('entries');
        if (!w) return;
        if (w.entriesAll || w.entryIds.has(String(id)) || w.entryUnits.size === 0) {
            /* 單筆沒明確載入但「有載入某些單元」時，可能是別人的單元 → 一律要求明確載入 */
        }
        if (w.entriesAll || w.entryIds.has(String(id))) return;
        throw windowMissing(`生字 ${id}`);
    }
    function requireAllEntries() {
        const w = needsWindow('entries');
        if (!w) return;
        if (!w.entriesAll) throw windowMissing('全部生字');
    }
    function requireAudioOf(entryId) {
        const w = needsWindow('audio');
        if (!w) return;
        if (w.audioAll || w.audioEntries.has(String(entryId))) return;
        throw windowMissing(`生字 ${entryId} 的音檔`);
    }
    function requireAllAudio() {
        const w = needsWindow('audio');
        if (!w) return;
        if (!w.audioAll) throw windowMissing('全部音檔');
    }
    function requireCounts() {
        const w = needsWindow('entries');
        if (!w) return;
        if (!w.countsLoaded && !w.countsAll) throw windowMissing('生字數統計');
    }
    /* 稽核視窗是「照某組篩選抓回來的」—— 用字串指紋確認路由問的是同一組，
     * 不同的話寧可拋錯，也不要回一份不是他要的資料（例如匯出拿到畫面上那 25 筆）。 */
    function auditFingerprint(options = {}) {
        const filters = normalizeAuditFilters(options);
        return [
            filters.q, filters.action, filters.user, filters.from, filters.to,
            options.limit || 50, options.offset || 0,
            options.hide_self_test === false ? 'all' : 'hide-self'
        ].join('|');
    }

    function requireAuditWindow() {
        const w = needsWindow('audit_logs');
        if (!w) return;
        if (!w.auditLoaded) throw windowMissing('稽核紀錄');
    }

    function emptyState() {
        const out = {};
        for (const name of TABLES) out[name] = [];
        return out;
    }

    function reset() {
        state = emptyState();
        nextId = {};
        ops = [];
        for (const name of TABLES) nextId[name] = 1;
        hydrated = false;
        hydratedAt = 0;
        hydrating = null;
    }
    reset();

    async function request(path, { method = 'GET', body, prefer } = {}) {
        const headers = {
            apikey: key,
            Authorization: `Bearer ${key}`,
            Accept: 'application/json'
        };
        if (body !== undefined) headers['Content-Type'] = 'application/json';
        if (prefer) headers.Prefer = prefer;
        const res = await fetch(`${url}/rest/v1/${path}`, {
            method,
            headers,
            body: body === undefined ? undefined : JSON.stringify(body)
        });
        const text = await res.text();
        let data = null;
        if (text) {
            try { data = JSON.parse(text); } catch (err) { data = text; }
        }
        if (!res.ok) {
            const message = (data && (data.message || data.hint || data.error)) || `HTTP ${res.status}`;
            const err = new Error(`Supabase ${method} ${path} → ${message}`);
            err.code = 'SUPABASE_REQUEST_FAILED';
            err.status = res.status;
            throw err;
        }
        return data;
    }

    /* PostgREST 的函式呼叫（RPC）：POST /rest/v1/rpc/<函式名>，body 是函式的具名參數。
     * ★ v0.7.0（D-1c／D-6）：`dict_entry_counts()` 與 `dict_db_size()` 就是這樣呼叫的。
     *   函式不存在時 PostgREST 回 404（PGRST202）→ 這裡會拋錯（大聲失敗，不靜默回空）。 */
    function rpc(fn, args = {}) {
        return request(`rpc/${fn}`, { method: 'POST', body: args });
    }

    /* 每個實例快取幾秒（ttl 預設 3000ms）：一次頁面載入會打 2～4 個 /api，
     * 只有第一個真的去資料庫抓，其餘都用同一份快取 —— 這是「每頁都慢」的主因之一。
     * 自己寫入成功後會立刻把快取時間戳更新（見 flush），所以不會看到自己的舊資料；
     * 別的實例的寫入最多晚 ttl 毫秒看到（學校規模完全夠用）。
     * 要更即時就把 SUPABASE_HYDRATE_TTL_MS 設小（0 = 每個請求都重抓）。 */
    const hydrateTtlMs = (() => {
        const fromOptions = Number(options.hydrateTtlMs);
        if (Number.isFinite(fromOptions) && options.hydrateTtlMs !== undefined) return fromOptions;
        const fromEnv = Number(process.env.SUPABASE_HYDRATE_TTL_MS);
        return Number.isFinite(fromEnv) ? fromEnv : 3000;
    })();

    /* `{ full: true }` = 連生字／音檔／稽核都整表抓（腳本、測試與沒有請求上下文時用）。
     * 有請求上下文時只抓小表（視窗由 prefetch 決定）。 */
    async function hydrate({ full = false } = {}) {
        const scope = (full || !win()) ? TABLES : HYDRATE_TABLES;
        /* 還有沒寫回的異動時不要重抓：重抓會把 state 換掉，那些寫入就憑空消失了 */
        if (ops.length) return state;
        if (hydrated && Date.now() - hydratedAt < hydrateTtlMs) return state;
        if (hydrating) return hydrating;
        hydrating = (async () => {
            const fresh = emptyState();
            try {
                const results = await Promise.all(scope.map((name) => request(
                    `${TABLE_PREFIX}${name}?select=${encodeURIComponent(SELECT_COLUMNS[name] || '*')}&order=id.asc`,
                    { prefer: 'count=exact' }
                )));
                scope.forEach((name, index) => {
                    const rows = Array.isArray(results[index]) ? results[index] : [];
                    /* 大欄位不在這份快取裡：明確設成 null，讓「有沒有封面」改看 cover_bytes */
                    const heavy = HEAVY_FIELDS[name];
                    if (heavy) for (const row of rows) row[heavy] = null;
                    fresh[name] = rows;
                    const maxId = rows.reduce((max, row) => Math.max(max, Number(row.id) || 0), 0);
                    nextId[name] = maxId + 1;
                });
                lastError = null;
            } catch (err) {
                lastError = { message: err.message, code: err.code || null, status: err.status || null, at: new Date().toISOString() };
                hydrating = null;
                throw err;
            }
            state = fresh;
            ops = [];
            hydrated = true;
            hydratedAt = Date.now();
            hydrating = null;
            return state;
        })();
        return hydrating;
    }

    /* ---------- 視窗化資料層：這一支請求需要什麼 ----------
     * 為什麼要有這張表：路由是同步的，資料必須「先抓好再進去」；
     * 把「哪條路由要哪些資料」集中寫在這裡，才不會散在十幾個地方。 */
    function planFor(spec = {}) {
        const method = String(spec.method || 'GET').toUpperCase();
        const path = String(spec.path || '').replace(/\/$/, '') || '/';
        const query = spec.query || {};
        const body = spec.body && typeof spec.body === 'object' ? spec.body : {};
        const plan = {
            entryUnits: new Set(),
            entryIds: new Set(),
            counts: false,
            audioAll: false,
            audit: null,
            totals: false,
            nextIds: method !== 'GET'          /* 只有寫入才需要配 id */
        };
        const unitMatch = /^\/units\/(\d+)/.exec(path);
        const entryMatch = /^\/entries\/(\d+)/.exec(path);

        /* 書架（年級）與目錄（單元）都要「每個單元的生字數」才能顯示統計 */
        if (path === '/books' || path === '/my/units' || /^\/books\/\d+\/units$/.test(path)
            || /^\/books\/\d+\/move$/.test(path) || /^\/books\/\d+$/.test(path)) {
            plan.counts = true;
        }
        /* 單元相關：這個單元的生字（含各狀態）＋它的音檔＋數字 */
        if (unitMatch) {
            plan.entryUnits.add(unitMatch[1]);
            plan.counts = true;
        }
        /* 單筆生字相關：先抓那一筆，再由 prefetch 追它的單元 */
        if (entryMatch) plan.entryIds.add(entryMatch[1]);
        /* 批次審核：前端送哪幾筆就抓哪幾筆 */
        if (path === '/entries/review-batch' && Array.isArray(body.ids)) {
            for (const id of body.ids) plan.entryIds.add(String(id));
        }
        /* 統計頁：全部生字的數字（不搬整列）＋全部音檔的中繼資料（算容量）＋資料庫大小 */
        if (path === '/admin/stats') {
            plan.counts = true;
            plan.audioAll = true;
            plan.nextIds = false;
            plan.dbSize = true;                          /* v0.7.0（D-6）：用量百分比 */
        }
        /* 稽核：照畫面上那組篩選抓一份切片（含總數） */
        if (/^\/admin\/audit-logs/.test(path)) plan.audit = { query };
        if (path === '/health') {
            plan.totals = true;
            plan.dbSize = true;                          /* v0.7.0（D-6）：健康檢查也回用量 */
        }
        return plan;
    }

    /* 真正去資料庫把這一支請求要的切片抓回來 */
    async function prefetch(spec = {}) {
        const w = win();
        if (!w) return;                                  /* full 模式：不需要（腳本／測試） */
        const plan = planFor(spec);
        /* 診斷用：STORE_DEBUG_PREFETCH=1 時印出「這條路由要抓哪些範圍」（不印任何資料內容） */
        const debugPrefetch = String(process.env.STORE_DEBUG_PREFETCH || '') === '1';
        if (debugPrefetch) {
            console.log('[prefetch]', spec.method, spec.path, JSON.stringify({
                entryUnits: Array.from(plan.entryUnits),
                entryIds: Array.from(plan.entryIds),
                counts: plan.counts,
                audioAll: plan.audioAll,
                audit: Boolean(plan.audit),
                totals: plan.totals,
                nextIds: plan.nextIds
            }));
        }

        /* (a) 生字數：**由資料庫聚合**（v0.7.0／D-1c）。
         * 以前是抓 `unit_id,status` 兩個欄位回來自己 bucket 計數（一萬筆約 200KB 的搬運量，
         * 每次快取過期都要再搬一次）；現在改叫 `dict_entry_counts()` 在資料庫裡 group by。
         * ★ 回傳形狀刻意與以前**完全一樣**（{unit_id, status, n}），
         *   所以 countEntries() 與 requireCounts() 一行都不用改。 */
        if (plan.counts) {
            const rows = await rpc('dict_entry_counts', { unit_ids: null });
            w.entryCounts = (Array.isArray(rows) ? rows : []).map((row) => ({
                unit_id: row.unit_id,
                status: row.status,
                n: Number(row.n) || 0
            }));
            w.countsLoaded = true;
        }

        /* (a2) 資料庫真正的大小（v0.7.0／D-6）：給 /api/health 與 /api/admin/stats 算用量百分比。
         * ★ 抓不到時（函式還沒建、權限沒開）**不讓整條路由失敗**，而是記下原因、
         *   讓 API 誠實回 `usage.available:false`（D-6 規格：不可以假裝是 0）。 */
        if (plan.dbSize) {
            try {
                const raw = await rpc('dict_db_size', {});
                const first = Array.isArray(raw) ? raw[0] : raw;
                const value = (first && typeof first === 'object') ? Number(Object.values(first)[0]) : Number(first);
                w.dbSize = Number.isFinite(value) && value >= 0 ? value : null;
                w.dbSizeError = Number.isFinite(value) ? null : 'dict_db_size() 回傳的不是數字';
            } catch (err) {
                w.dbSize = null;
                w.dbSizeError = err.message;
            }
        }

        /* (b) 單筆生字：抓回來之後把它的單元也一起抓（改生字要檢查同單元重複） */
        if (plan.entryIds.size) {
            const ids = Array.from(plan.entryIds).map(encodeURIComponent).join(',');
            const rows = await request(`${TABLE_PREFIX}entries?id=in.(${ids})&select=*`);
            for (const row of (Array.isArray(rows) ? rows : [])) {
                w.entries.push(row);
                w.entryIds.add(String(row.id));
                /* 一律把它所屬單元的生字一起抓（改生字要檢查同單元是否重複、錄音要算單元用量） */
                w.entryUnits.add(String(row.unit_id));
                plan.entryUnits.add(String(row.unit_id));
            }
        }

        /* (c) 整批生字（一個或多個單元） */
        if (plan.entryUnits.size) {
            const ids = Array.from(plan.entryUnits).map((id) => encodeURIComponent(id)).join(',');
            const rows = await request(`${TABLE_PREFIX}entries?unit_id=in.(${ids})&select=*&order=sort_order.asc,id.asc`);
            for (const row of (Array.isArray(rows) ? rows : [])) {
                if (w.entryIds.has(String(row.id)) || w.entries.some((e) => String(e.id) === String(row.id))) continue;
                w.entries.push(row);
            }
            for (const id of plan.entryUnits) w.entryUnits.add(String(id));
        }

        /* (d) 音檔：只抓 (b)(c) 選到的生字的音檔 */
        if (plan.audioAll) {
            const rows = await request(`${TABLE_PREFIX}audio?select=${encodeURIComponent(SELECT_COLUMNS.audio)}&limit=100000`);
            w.audio = Array.isArray(rows) ? rows : [];
            for (const row of w.audio) row.data = null;
            w.audioAll = true;
        } else if (w.entries.length) {
            const ids = w.entries.map((row) => encodeURIComponent(row.id));
            /* 一次最多 200 個 id，避免 URL 太長（一個單元不可能那麼多筆同時要，超過就分批） */
            for (let i = 0; i < ids.length; i += 200) {
                const chunk = ids.slice(i, i + 200).join(',');
                const rows = await request(`${TABLE_PREFIX}audio?entry_id=in.(${chunk})&select=${encodeURIComponent(SELECT_COLUMNS.audio)}`);
                for (const row of (Array.isArray(rows) ? rows : [])) {
                    row.data = null;                        /* 大欄位不進記憶體 */
                    w.audio.push(row);
                }
            }
            for (const row of w.entries) w.audioEntries.add(String(row.id));
        }

        /* (e) 稽核：照路由的篩選抓一份（含 count） */
        if (plan.audit) {
            const w2 = w;
            const options = { ...plan.audit.query };
            const filters = normalizeAuditFilters(options);
            const limit = Math.min(Number(options.limit) || 50, 1000);
            const offset = Number(options.offset) || 0;
            const parts = ['select=*', 'order=created_at.desc,id.desc', `limit=${limit}`, `offset=${offset}`];
            const escape = (value) => encodeURIComponent(value);
            if (filters.action) parts.push(`action=eq.${escape(filters.action)}`);
            if (filters.from) parts.push(`created_at=gte.${escape(filters.from)}`);
            if (filters.to) parts.push(`created_at=lte.${escape(filters.to)}`);
            if (options.hide_self_test === false) { /* 不篩 */ } else parts.push('is_self_test=eq.false');
            if (filters.user) {
                const like = `*${filters.user}*`;
                parts.push(`or=(display_name.ilike.${escape(like)},user_id.eq.${escape(filters.user)})`);
            }
            if (filters.q) {
                const like = `*${filters.q}*`;
                parts.push(`or=(action.ilike.${escape(like)},details.ilike.${escape(like)},display_name.ilike.${escape(like)})`);
            }
            const res = await fetch(`${url}/rest/v1/${TABLE_PREFIX}audit_logs?${parts.join('&')}`, {
                headers: {
                    apikey: key,
                    Authorization: `Bearer ${key}`,
                    Accept: 'application/json',
                    Prefer: 'count=exact'
                }
            });
            const bodyText = await res.text();
            if (!res.ok) {
                const err = new Error(`Supabase 稽核視窗 → HTTP ${res.status}：${bodyText.slice(0, 200)}`);
                err.code = 'SUPABASE_REQUEST_FAILED';
                throw err;
            }
            const range = res.headers.get('content-range') || '';
            const total = Number(String(range).split('/')[1]) || 0;
            w2.audit = bodyText ? JSON.parse(bodyText) : [];
            w2.auditTotal = total;
            w2.auditFingerprint = auditFingerprint(options);
            w2.auditLoaded = true;
        }

        /* (f) 各表筆數（/api/health） */
        if (plan.totals) {
            const totals = {};
            for (const name of TABLES) {
                const res = await fetch(`${url}/rest/v1/${TABLE_PREFIX}${name}?select=id&limit=1`, {
                    headers: { apikey: key, Authorization: `Bearer ${key}`, Accept: 'application/json', Prefer: 'count=exact' }
                });
                const range = res.headers.get('content-range') || '';
                totals[name] = Number(String(range).split('/')[1]) || 0;
            }
            w.totals = totals;
        }

        /* (g) 配 id 用的最大值（寫入才需要） */
        if (plan.nextIds) {
            for (const name of WINDOW_TABLES) {
                const rows = await request(`${TABLE_PREFIX}${name}?select=id&order=id.desc&limit=1`);
                const maxId = (Array.isArray(rows) ? rows : []).reduce((max, row) => Math.max(max, Number(row.id) || 0), 0);
                nextId[name] = maxId + 1;
                if (name === 'entries') nextId.entries = maxId + 1;
                if (debugPrefetch) console.log('[nextIds]', name, 'maxId=', maxId, 'rows=', JSON.stringify(rows).slice(0, 80));
            }
        }
        return w;
    }

    /* 請求上下文的入口：middleware 用這三個 */
    function attach() { return newWindow(); }
    function runWithContext(context, fn) { return als.run(context, fn); }
    /* 診斷用：只吐「不含機密」的資訊（主機代號、金鑰的角色與所屬專案 ref、最後一次錯誤）。
     * ★ 不要把金鑰本身或它的雜湊放進來 —— /api/health 是公開端點。 */
    function diagnostics() {
        let role = null;
        let ref = null;
        let format = 'jwt';
        try {
            const payload = JSON.parse(Buffer.from(String(key).split('.')[1] || '', 'base64url').toString('utf8'));
            role = payload.role || null;
            ref = payload.ref || null;
        } catch (err) {
            format = 'not-a-jwt';
        }
        return {
            host: String(url).replace(/^https?:\/\//, '').split('.')[0] || null,
            key_role: role,
            key_ref: ref,
            key_format: format,
            hydrate_ok: !lastError,
            last_error: lastError
        };
    }

    /* 把某張表的異動寫回；一次一筆，順序固定（外鍵不會踩到） */
    async function applyOps(list) {
        for (const op of list) {
            const table = `${TABLE_PREFIX}${op.table}`;
            if (op.kind === 'insert') {
                await request(table, { method: 'POST', body: op.row, prefer: 'return=minimal' });
            } else if (op.kind === 'update') {
                await request(`${table}?id=eq.${encodeURIComponent(op.id)}`, { method: 'PATCH', body: op.patch, prefer: 'return=minimal' });
            } else if (op.kind === 'delete') {
                await request(`${table}?id=eq.${encodeURIComponent(op.id)}`, { method: 'DELETE', prefer: 'return=minimal' });
            }
        }
    }

    async function flush() {
        if (!ops.length) return { written: 0 };
        const pending = ops;
        ops = [];
        const ordered = [
            ...pending.filter((op) => op.kind === 'delete').sort((a, b) => DELETE_ORDER.indexOf(a.table) - DELETE_ORDER.indexOf(b.table)),
            ...pending.filter((op) => op.kind === 'insert').sort((a, b) => INSERT_ORDER.indexOf(a.table) - INSERT_ORDER.indexOf(b.table)),
            ...pending.filter((op) => op.kind === 'update')
        ];
        try {
            await applyOps(ordered);
        } catch (err) {
            /* 失敗就把異動丟掉、並讓下一次請求重新 hydrate：
             * 記憶體不可以留著「其實沒寫進資料庫」的假資料（會讓使用者以為存好了）。 */
            ops = [];
            hydrated = false;
            hydratedAt = 0;
            throw err;
        }
        /* 自己剛寫完，記憶體與資料庫一致 → 把快取時間戳往後推，不用再抓一次 */
        hydratedAt = Date.now();
        return { written: ordered.length };
    }

    /* ---------- 內部：讀寫記憶體 ---------- */
    const clone = (value) => (value === undefined || value === null ? value : JSON.parse(JSON.stringify(value)));

    function rows(table) { return state[table] || (state[table] = []); }

    function insert(table, data) {
        const row = Object.assign({}, data);
        if (row.id === undefined || row.id === null) {
            row.id = nextId[table] || 1;
            nextId[table] = row.id + 1;
        }
        if (row.created_at === undefined) row.created_at = new Date().toISOString();
        /* v0.6.0：新增的列也要有 updated_at（樂觀鎖 D-2 要用）
         * ★ 但只有「真的有這個欄位」的表才可以寫：dict_audit_logs／dict_audio／dict_grants 沒有 updated_at，
         *   硬寫下去 Supabase 會回 42703（Could not find the 'updated_at' column）→ 整個寫入失敗。 */
        if (HAS_UPDATED_AT.has(table) && row.updated_at === undefined) row.updated_at = row.created_at;
        heavyRows(table).push(row);
        /* 新建的生字：音檔視窗本來就是空的，先記下來免得被守門擋住 */
        if (table === 'entries' && row.unit_id !== undefined) {
            const w = win();
            if (w) { w.createdEntryIds.add(String(row.id)); w.entryUnits.add(String(row.unit_id)); }
        }
        ops.push({ kind: 'insert', table, row: clone(row) });
        return clone(row);
    }

    function update(table, id, patch) {
        const list = heavyRows(table);
        const row = list.find((r) => String(r.id) === String(id));
        if (!row) return null;
        /* v0.6.1：只有真的有 updated_at 欄位的表才寫它（audit_logs／audio／grants 沒有） */
        if (HAS_UPDATED_AT.has(table)) patch = Object.assign({}, patch, { updated_at: new Date().toISOString() });
        Object.assign(row, patch);
        ops.push({ kind: 'update', table, id: row.id, patch: Object.assign({}, patch) });
        return clone(row);
    }

    function remove(table, id) {
        const list = heavyRows(table);
        const index = list.findIndex((r) => String(r.id) === String(id));
        if (index === -1) return false;
        list.splice(index, 1);
        ops.push({ kind: 'delete', table, id });
        return true;
    }

    function sorted(table, compare) {
        return rows(table).slice().sort(compare).map(clone);
    }

    /* ---------- 書本 ---------- */
    function listBooks({ includeUnpublished = false } = {}) {
        return sorted('books', (a, b) => (a.sort_order - b.sort_order) || (a.id - b.id))
            .filter((b) => includeUnpublished || b.is_published !== false);
    }
    function getBook(id) { return clone(rows('books').find((b) => String(b.id) === String(id))) || null; }
    function createBook(data) { return insert('books', data); }
    function updateBook(id, patch) { return update('books', id, patch); }

    /* ---------- 單元 ---------- */
    function listUnits({ bookId = null, includeUnpublished = false } = {}) {
        return sorted('units', (a, b) => (a.unit_no - b.unit_no) || (a.id - b.id))
            .filter((u) => (bookId === null || String(u.book_id) === String(bookId)))
            .filter((u) => includeUnpublished || u.is_published !== false);
    }
    function getUnit(id) { return clone(rows('units').find((u) => String(u.id) === String(id))) || null; }
    function findUnitByNo(bookId, unitNo) {
        return clone(rows('units').find((u) => String(u.book_id) === String(bookId) && Number(u.unit_no) === Number(unitNo))) || null;
    }
    function createUnit(data) { return insert('units', data); }
    function updateUnit(id, patch) { return update('units', id, patch); }

    /* ---------- 生字 ---------- */
    function listEntries({ unitId = null, statuses = null } = {}) {
        if (unitId === null) requireAllEntries();
        else requireEntriesOfUnit(unitId);
        const list = heavyRows('entries').slice()
            .sort((a, b) => (a.sort_order - b.sort_order) || (a.id - b.id))
            .map(clone);
        const target = unitId === null ? list : list.filter((e) => String(e.unit_id) === String(unitId));
        return target.filter((e) => !statuses || statuses.includes(e.status));
    }
    function getEntry(id) {
        requireEntry(id);
        return clone(heavyRows('entries').find((e) => String(e.id) === String(id))) || null;
    }
    function findEntryByHeadword(unitId, headwordNorm) {
        requireEntriesOfUnit(unitId);
        return clone(heavyRows('entries').find((e) => String(e.unit_id) === String(unitId) && e.headword_norm === headwordNorm)) || null;
    }
    function createEntry(data) { return insert('entries', data); }
    function updateEntry(id, patch) { return update('entries', id, patch); }
    function deleteEntry(id) {
        requireAudioOf(id);
        const ok = remove('entries', id);
        if (ok) {
            for (const audio of heavyRows('audio').filter((a) => String(a.entry_id) === String(id))) remove('audio', audio.id);
        }
        return ok;
    }
    /* 生字數：優先用工作集裡的完整生字（精確），否則用 prefetch 抓回來的 {unit_id,status,n} 小表 */
    function countEntries(unitId, statuses) {
        const w = win();
        const loaded = w ? (w.entriesAll || w.entryUnits.has(String(unitId))) : true;
        if (loaded) {
            return heavyRows('entries')
                .filter((e) => String(e.unit_id) === String(unitId))
                .filter((e) => !statuses || statuses.includes(e.status)).length;
        }
        requireCounts();
        return (w ? w.entryCounts : [])
            .filter((row) => String(row.unit_id) === String(unitId))
            .filter((row) => !statuses || statuses.includes(row.status))
            .reduce((sum, row) => sum + Number(row.n || 0), 0);
    }
    /* 全部生字的數字（統計頁用；不需要把整表搬進記憶體） */
    function countAllEntries() {
        const w = win();
        if (!w || w.entriesAll) {
            const all = heavyRows('entries');
            const out = { total: all.length, published: 0, pending: 0, rejected: 0 };
            for (const row of all) if (out[row.status] !== undefined) out[row.status] += 1;
            return out;
        }
        requireCounts();
        const out = { total: 0, published: 0, pending: 0, rejected: 0 };
        for (const row of w.entryCounts) {
            const n = Number(row.n || 0);
            out.total += n;
            if (out[row.status] !== undefined) out[row.status] += n;
        }
        return out;
    }

    /* ---------- 音檔 ---------- */
    function listAudio({ entryId = null } = {}) {
        if (entryId === null) requireAllAudio();
        else requireAudioOf(entryId);
        return heavyRows('audio')
            .filter((a) => (entryId === null || String(a.entry_id) === String(entryId)))
            .map(clone);
    }
    function getAudio(id) { return clone(rows('audio').find((a) => String(a.id) === String(id))) || null; }
    /* 音檔內容（base64）不在快取裡，要的時候才單筆抓 —— 見檔頭 SELECT_COLUMNS 的說明 */
    async function getAudioData(id) {
        const found = await request(`${TABLE_PREFIX}audio?id=eq.${encodeURIComponent(id)}&select=data,mime,bytes`);
        const row = Array.isArray(found) ? found[0] : null;
        return row || null;
    }
    async function getBookCoverData(id) {
        const found = await request(`${TABLE_PREFIX}books?id=eq.${encodeURIComponent(id)}&select=cover_data,cover_mime,cover_bytes`);
        const row = Array.isArray(found) ? found[0] : null;
        return row || null;
    }
    function createAudio(data) { return insert('audio', data); }
    function deleteAudio(id) { return remove('audio', id); }
    function findTeacherAudio(entryId) {
        const w = win();
        /* 這個請求剛新建的生字：音檔視窗當然是空的（不用守門） */
        if (w && w.createdEntryIds.has(String(entryId))) return null;
        requireAudioOf(entryId);
        return clone(heavyRows('audio').find((a) => String(a.entry_id) === String(entryId) && a.source === 'teacher')) || null;
    }

    /* ---------- 使用者 ---------- */
    function findUserByUsername(username) {
        const key2 = String(username || '').trim().toLowerCase();
        return clone(rows('users').find((u) => String(u.username || '').toLowerCase() === key2)) || null;
    }
    function getUser(id) { return clone(rows('users').find((u) => String(u.id) === String(id))) || null; }
    function listUsers() { return sorted('users', (a, b) => a.id - b.id); }
    function createUser(data) { return insert('users', data); }
    function updateUser(id, patch) { return update('users', id, patch); }
    function deleteUser(id) { return remove('users', id); }
    function countUsersByRole(role) {
        return rows('users').filter((u) => u.role === role && u.is_active !== false).length;
    }

    /* ---------- 授權 ---------- */
    function listGrants({ userId = null } = {}) {
        return rows('grants')
            .filter((g) => (userId === null || String(g.user_id) === String(userId)))
            .map(clone);
    }
    function createGrant(data) { return insert('grants', data); }
    function deleteGrant(id) { return remove('grants', id); }

    /* ---------- 稽核 ---------- */
    function insertAuditLog(row) { return insert('audit_logs', row); }
    /* 刪除單筆稽核紀錄（A-3 的保留期清理用）：走既有的 delete op，回應前 flush 寫回 */
    function deleteAuditLog(id) {
        return remove('audit_logs', id);
    }

    function listAuditLogs(options = {}) {
        const w = win();
        if (w) {
            requireAuditWindow();
            const fingerprint = auditFingerprint(options);
            if (w.auditFingerprint !== fingerprint) {
                throw windowMissing(`稽核紀錄（這組篩選 ${fingerprint}）`);
            }
        }
        const filters = normalizeAuditFilters(options);
        const limit = options.limit || 50;
        const offset = options.offset || 0;
        const matched = heavyRows('audit_logs')
            .filter((row) => matchesAuditFilters(row, filters))
            .sort((a, b) => (a.created_at < b.created_at ? 1 : a.created_at > b.created_at ? -1 : b.id - a.id));
        const page = matched.slice(offset, offset + limit).map(clone);
        const total = w ? w.auditTotal : matched.length;
        return { items: page, total, limit, offset, has_more: offset + page.length < total };
    }

    function tableCounts() {
        const w = win();
        if (w && w.totals) return Object.assign({}, w.totals);
        const counts = {};
        for (const name of TABLES) counts[name] = heavyRows(name).length;
        return counts;
    }

    /* D-6：資料庫用量。真實大小是在 prefetch 時用 `dict_db_size()` 抓的（見 plan.dbSize）；
     * ★ 拿不到就回 `available:false` 並附原因 —— 寧可說「不知道」，也不要回 0 假裝很空。 */
    function dbUsage() {
        const { usageState } = require('../limits');
        const w = win();
        const bytes = w && Number.isFinite(w.dbSize) ? w.dbSize : null;
        const reason = w && w.dbSizeError
            ? w.dbSizeError
            : (w ? '這次請求沒有抓資料庫大小（見 planFor 的 dbSize）' : '沒有請求上下文（腳本／測試請直接呼叫 rpc）');
        return usageState(bytes, { source: 'dict_db_size()', reason });
    }

    return {
        backend: 'supabase',
        dataFile: null,
        normalizeHeadword: require('./index').normalizeHeadword,
        hydrate,
        flush,
        diagnostics,
        /* v0.6.1：視窗化資料層（middleware 會用） */
        attach,
        prefetch,
        runWithContext,
        planFor,
        listBooks, getBook, createBook, updateBook,
        listUnits, getUnit, findUnitByNo, createUnit, updateUnit,
        listEntries, getEntry, findEntryByHeadword, createEntry, updateEntry, deleteEntry, countEntries, countAllEntries,
        listAudio, getAudio, getAudioData, createAudio, deleteAudio, findTeacherAudio,
        getBookCoverData,
        findUserByUsername, getUser, listUsers, createUser, updateUser, deleteUser, countUsersByRole,
        listGrants, createGrant, deleteGrant,
        insertAuditLog, listAuditLogs, deleteAuditLog,
        tableCounts,
        dbUsage,
        reload: reset,
        pendingOps: () => ops.length,
        _raw: () => clone(state)
    };
}

module.exports = { createSupabaseStore, TABLES, INSERT_ORDER, DELETE_ORDER };
